services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${DOCKER_HTTP_PORT}:80"
    volumes:
      - ./:/var/www:delegated
      - ./storage/app/public/:/var/www/public/storage:delegated
      - node_modules:/var/www/node_modules
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      - nginx-proxy
      - default
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: development
    volumes:
      - ./:/var/www:delegated
    networks:
      - default

  # Database Service
  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: kennen_portfolio
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - dbdata:/var/lib/mysql:rw
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - default

# Docker Networks
networks:
  default:
    driver: bridge
  nginx-proxy:
    external: true

# Volumes
volumes:
  node_modules:
  dbdata:
    driver: local