services:
  #Nginx Service
  nginx:
    image: nginx:alpine
    links:
      - php
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      # - "443:443"
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PORT=80
    volumes:
      - ./:/var/www:delegated
      - ./storage/app/public/:/var/www/public/storage:delegated
      - node_modules:/var/www/node_modules #effectively allows it to be ignored
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      nginx-proxy:
        aliases:
          - api.kennen.local
      default:
    hostname: api.kennen.local

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    entrypoint: ["/var/www/docker/php/docker-entrypoint.sh"]
    volumes:
      - ./:/var/www:delegated
    networks:
      - default
    command: ["php-fpm"]

  #Database Service
  db:
    image: mysql:8.0.41
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: kennen_portfolio
      SERVICE_NAME: mysql
    volumes:
      - ${DOCKER_DBDATA_SOURCE}:/var/lib/mysql/:rw
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - default

#Docker Networks
networks:
  default:
    driver: bridge
  nginx-proxy:
    external: true
    name: nginx-proxy
      
#Volumes
volumes:
  node_modules:
  dbdata:
    driver: local

  # app:
  #   build: .
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - .:/var/www
